### ISSUE TITLE
Authentication failed with github 2 FA

### ISSUE THREAD

**Issue by jimmidyson** [ekonstantinidis/trevor#66]
Can log in supposedly successfully, granted permissions to Trevor as required but get an Oops, can't login response when redirected back to the app. This is on android.

Any ideas?

**Comment by zbeekman** [comment]
Same issue here on iPhone. Currently useless...

**Comment by zbeekman** [comment]
ping @ekonstantinidis

**Comment by ekonstantinidis** [comment]
Hi there! I've started some works on Version 2 (made with React Native) but I guess it is worth fixing that bug for now. Will have a look soon!

**Comment by ekonstantinidis** [comment]
**Update**:

@jimmidyson  @zbeekman So I've spent sometime bringing the app up to date - reverting back to Ionic on master, updating for Cordova 5 etc and also had a look on what could be wrong about the authentication with Travis for Open Source.

So since the app hasn't changed at all, I tried to authenticate with Travis but I keep getting the error:

> you are currently not allowed to perform this request. please contact support@travis-ci.com.

I guess something has changed / is broken on the API so I've sent an email to the Travis folks describing the issue. Once I get a response I let you know. Thanks for mentioning the issue :smile: 

Ps. Once we solve this issue I will be happy to have a look to Two Factor Authentication.

**Comment by zbeekman** [comment]
I'm not sure if the issue is actually caused by 2FA or just a problem with the app talking to travis through the API... The app and travis use github to authenticate, and I doubt travis or trevor need to do anything differently. So my suspicion, upon hearing your update, is that the 2FA was just a red herring and that Trevor was broken for everyone.

**Comment by zbeekman** [comment]
p.s. thanks for working on this. Your app looks really nice, so I am excited to be able to actually try it.

**Comment by ekonstantinidis** [comment]
I've got good news :smile: So I was informed that Travis was under a DDOS attack and they had to allow requests only from whitelisted `User-Agents`. Trevor was trying to set the `User-Agent` but it actually wasn't since Cordova requires a setting under `config.xml`. I've just submitted a new update (`1.8.0`) which fixes this issue and it also includes an updated version of Ionic & Angular.

I hope that Apple will approve it soon and you will have it once available!

<img width="1378" alt="screen shot 2015-12-21 at 22 34 56" src="https://cloud.githubusercontent.com/assets/6333409/11943651/808b7d96-a837-11e5-8e20-76b64bf6d8e9.png">

**Comment by zbeekman** [comment]
Any updates?

**Comment by ekonstantinidis** [comment]
@zbeekman It looks like it is taking too long for Apple to review. :disappointed:  Even though the average(unofficial - http://appreviewtimes.com/) is 7 days, we are waiting for 15 days now. Hopefully they will approve it during the next couple of days :tada: 

![screen shot 2016-01-04 at 10 49 34](https://cloud.githubusercontent.com/assets/6333409/12088191/ef1c2906-b2d0-11e5-964d-b811eb51c1aa.png)

**Comment by zbeekman** [comment]
OK, thanks for the update. If there's anyway that users can express interest in the app to help speed the review process let me know.

**Comment by ekonstantinidis** [comment]
Approved! Should be on the app store shortly :tada: Will submit to Google Play store tomorrow too!
![image](https://cloud.githubusercontent.com/assets/6333409/12131214/8dbba450-b408-11e5-82cb-70b54c69c5cc.png)
